#declared pins of each pump
PUMP_GIN_PIN = 23
PUMP_TONIC_PIN = 24
PUMP_MANGO_PIN = 4
PUMP_VODKA_PIN = 14
PUMP_ORANGE_PIN = 15
PUMP_COFFEE_PIN = 17
PUMP_LEMONADE_PIN = 18
PUMP_EIGHT_PIN = 27

#all values necessary to set up the load cell
dataPin = 19
clockPin = 26
refUnit = 228
offset = -147830

#specific weights of each cocktail component in grams
GIN_WEIGHT_GINTONIC = 100
GIN_WEIGHT_GINHASS = 100
GIN_WEIGHT_SUMMERCOLLINS = 100
TONIC_WEIGHT_GINTONIC =100
TONIC_WEIGHT_GINHASS = 100
MANGO_WEIGHT= 100
VODKA_WEIGHT_SCREWDRIVER =100
VODKA_WEIGHT_BLACKRUSSIAN = 100 
ORANGE_WEIGHT =100
COFFEE_WEIGHT =100
LEMONADE_WEIGHT = 100

